<?php

echo "<h1>Twitter API</h1>";

echo $this->tag->linkTo("twitter/retweet", "retweet");
echo "<br>";
echo $this->tag->linkTo("twitter/like", "like");
echo "<br>";
echo $this->tag->linkTo("twitter/uploadAvatar", "update avatar");
echo "<br>";
echo $this->tag->linkTo("twitter/getListFollower", "check follower");
echo "<br>";
echo $this->tag->linkTo("twitter/follow", "follow");
echo "<br>";
echo $this->tag->linkTo("twitter/sort", "sort");
